sudo: required
services:
  - docker

before_install:
  - docker build -t lokcc/docker-react-2 -f Dockerfile.dev .

script:
  - docker run -e CI=true lokcc/docker-react-2 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-2"
  env: "Dockerreact2-env"
  bucket_name: "elasticbeanstalk-us-east-2-146622960778"
  bucket_path: "docker-react-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
